[build]
# Chỉ định sử dụng Docker để build
builder = "Docker"

[deploy]
# Environment variables cho Redis và PostgreSQL
envs = {
  REDIS_URL = "redis://<your-redis-url>",
  DB_CONNECTION_STRING = "postgres://<your-db-url>",
}

# Cấu hình service chính (atproto)
services = [
  {
    name = "atproto",
    build = ".",
    start = "make run-dev-env"
  }
]

[plugins]
# Cấu hình Redis và PostgreSQL plugin
postgresql = { plan = "starter" }
redis = { plan = "starter" }
